name: shapeup
description: "Aplicativo para gestão de treinos e dietas - ShapeUp"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  # Firebase (linha 4.x estável p/ Flutter 3.x)
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  shared_preferences: ^2.2.2
  # fl_chart: ^1.1.0
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  # Login Google
  google_sign_in: ^7.1.1

  # Estado / utilidades
  provider: ^6.1.2
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - imagens/LogoVazada.png
